### PR TITLE
fixes #137 : Unexpected identifier when querying  with strings that have ['] character

### LINKED ISSUE #137: Unexpected identifier when querying $in with strings that have ['] character
Hi,

I'm using TingoDB version 0.4.2, downloaded from npm and when i'm querying a String with ['] character, an exception has been raised (SyntaxError: Unexpected identifier). 
For example, when i run this query: 

{"serie":
       {"$in":["Marvel's Agents of S.H.I.E.L.D"]}
}

I get the following stack trace:

SyntaxError: Unexpected identifier
    at tcoll.__find (.../node_modules/tingodb/lib/tcoll.js:1083:83)
    at .../node_modules/tingodb/lib/tcoll.js:1126:8
    at wqueue._exec (.../node_modules/tingodb/lib/wqueue.js:36:3)
    at .../node_modules/tingodb/lib/wqueue.js:32:9
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:332:13
    at task (.../node_modules/tingodb/node_modules/safe/lib/safe.js:642:8)
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:656:8
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:342:13
    at .../node_modules/tingodb/lib/tcoll.js:174:4
    at _fnApply (.../node_modules/tingodb/node_modules/safe/lib/safe.js:173:22)

Any string with normal characters works fine.

### PR DESCRIPTION
**Pull request by diogoduailibe**
This solution fixes #137 : Unexpected identifier when querying  with strings that have ['] character.

### CODE REVIEW

**Comment by sergeyksv** [comment]
I afraid this will breaks opposite issue, double quote in search text.

**Comment by diogoduailibe** [comment]
I ran my fork on Travis CI before send this pull request to ensure that all tests wouldn't break master. Could you give an example where it could break?

**Comment by sergeyksv** [comment]
Something like `{"serie":{"$in":['Marvel "Agents of S.H.I.E.L.D"']}}`

**Comment by diogoduailibe** [comment]
I decided to undo this pull request. I'll try another solution and if both cases work, i will send another one. Thank's.

**Comment by sergeyksv** [comment]
Thank's a lot

**Pull request closed without merging**
