### PR TITLE
fixes #137 : Unexpected identifier when querying  with strings that have ['] character[2]

### LINKED ISSUE #137: Unexpected identifier when querying $in with strings that have ['] character
Hi,

I'm using TingoDB version 0.4.2, downloaded from npm and when i'm querying a String with ['] character, an exception has been raised (SyntaxError: Unexpected identifier). 
For example, when i run this query: 

{"serie":
       {"$in":["Marvel's Agents of S.H.I.E.L.D"]}
}

I get the following stack trace:

SyntaxError: Unexpected identifier
    at tcoll.__find (.../node_modules/tingodb/lib/tcoll.js:1083:83)
    at .../node_modules/tingodb/lib/tcoll.js:1126:8
    at wqueue._exec (.../node_modules/tingodb/lib/wqueue.js:36:3)
    at .../node_modules/tingodb/lib/wqueue.js:32:9
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:332:13
    at task (.../node_modules/tingodb/node_modules/safe/lib/safe.js:642:8)
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:656:8
    at .../node_modules/tingodb/node_modules/safe/lib/safe.js:342:13
    at .../node_modules/tingodb/lib/tcoll.js:174:4
    at _fnApply (.../node_modules/tingodb/node_modules/safe/lib/safe.js:173:22)

Any string with normal characters works fine.

### PR DESCRIPTION
**Pull request by diogoduailibe**
Hi sergeyksv,
I remembered that JSON.stringify does the trick. So i replaced all ocurrences of "'" with it. I ran travis CI on my fork and all tests were ok (except the node version 0.8 test that isn't working). Is this a good solution for you or Do you think that it could break something?

### CODE REVIEW

**Comment by sergeyksv** [comment]
Hi @diogoduailibe. Looks good. Do you mind to exclude 0.8 from test mattrix as part of this request. Thanks.

**Comment by diogoduailibe** [comment]
Hi @sergeyksv,

I've done what you asked me. I commented the 0.8 version line on travis.yml.

**Comment by sergeyksv** [comment]
@diogoduailibe thank you for your contribution

**Comment by diogoduailibe** [comment]
@sergeyksv Thank you for let me contribute.

**Pull request merged**
